lib/ledge/ledge.lua
t/18-on_abort.t

This is a bit of a weird one, I can only seem to reproduce it when the nginx upstream/proxy module is talking to Ledge.
When the Ledge server hits the `keepalive_requests` limit the abort handler is triggered and an error is thrown `attempt to set ngx.status after sending out response headers`
```
2015/05/29 11:13:13 [debug] 23794#0: *14 [lua] ledge.lua:1716: e(): #a: redis_close
2015/05/29 11:13:13 [info] 23794#0: *14 client prematurely closed connection, client: 185.64.252.20, server: dev.local, request: "GET /bench.html HTTP/1.1", host: "dev.local"
2015/05/29 11:13:13 [debug] 23794#0: *14 [lua] ledge.lua:1731: e(): #e: aborted
2015/05/29 11:13:13 [debug] 23794#0: *14 [lua] ledge.lua:1758: e(): #a: set_http_client_abort
2015/05/29 11:13:13 [error] 23794#0: *14 attempt to set ngx.status …
```

Do not attempt to set ngx.status in abort handler

---

lib/ledge/ledge.lua
t/03-events.t

@pintsized requests with quoted characters are getting munged by ledge. This PR allows us to get the unmunged route and pass it through to the origin.

Allow customisation of uri & params

---

lib/ledge/esi.lua
t/10-esi.t

Include tags without a space before closing weren't picked up, we should just ignore whitespace within the tag.
Also switched to square bracket string delimiter to avoid constantly escaping doublequotes.

Fix for whitespace in esi include tag

---

lib/ledge/jobs/purge.lua
t/14-purge.t

Currently if a wildcard purge scan loop hits a cache key with a broken entity it will `return nil, err`
Where err is often empty or ngx_null, this causes the whole job to abort with 'redis-error' and no message.
Change is to log the broken entity and continue with the SCAN process allowing the job to purge and revalidate subsequent cache entries.

Purge revalidate continues when an cache entry is broken

---

lib/ledge/ledge.lua
t/08-cache.t

As the new data structure only has 1 hash per cache entry for the headers, reval_params etc.
Calling `hmset()` on them with an updated set of headers from the origin overrides existing headers but does not purge old entries from the hash.
e.g.
Cache exists with headers
```
Date: Tue, 18 Oct 2016 11:47:36 GMT
Server: FooBar
X-Test: 123
```
New request comes in and goes to the origin, returns cacheable response with headers
```
Date: Tue, 19 Oct 2016 11:47:36 GMT
Server: BazQux
X-Test2: abc
```
Cache entry now contains
```
Date: Tue, 19 Oct 2016 11:47:36 GMT
Server: BazQux
X-Test: 123
X-Test2: abc
```
I think the correct solution to this is just to `redis:del()` every key before calling `hmset()`.

Hash append bug

---

lib/ledge/ledge.lua
t/08-cache.t

According to the HTTP1.1 spec only the no-cache and private headers support the no-cache="header" syntax to drop headers from the cache.
no-store doesn't support this.
Previous implementation didn't support headers with numbers in.
Also optimise the implementation to use ngx.re.find instead of string.gmatch.
Can be ~3x faster in some cases (e.g. multiple tokens across multiple headers)
```
baseline  - 100000 runs in 294.771 ms - avg: 0.0029
optimised - 100000 runs in 80.601 ms - avg: 0.0008
```

Fix no-cache=header implementation

---

lib/ledge/ledge.lua
t/10-esi.t

Non-Chrome browsers seem to use local cache when Last-Modified or Etag is sent alongside Cache-Control: private, must-revalidate
Setting max-age=0 forces a request with revalidation headers which can be 304'd by Ledge

Use max-age=0 instead of must-revalidate

---

lib/ledge/ledge.lua
t/10-esi.t

Currently the `Surrogate-Capability` device-token has to match the Host header in the request.
Little bit hacky, this fix uses get_header_token but passes in a regex matching 1 or more <tchar>
We should probably look at a proper header parsing lib of some kind

Fix Surrogate-Capability parsing

---

lib/ledge.lua
lib/ledge/handler.lua

Can't have default nil's in the current implementation, they become an unknown config option.
Also a minor typo in an error message

Fix setting resty_upstream handler option

---

README.md
lib/ledge.lua
lib/ledge/handler.lua
lib/ledge/response.lua
lib/ledge/state_machine/actions.lua
t/02-integration/upstream_client.t

Adds new feature handler.upstream_client
Removes `use_resty_upstream` flag and `resty_upstream` config options 
Adds `before_upstream_connect` event, use this to set handler.upstream_client to module compatible with resty.http
Always log connection errors in default upstream client

Resty upstream

---

lib/ledge/handler.lua

ran into this this morning - one of our data providers just started handing us multiple Via (and other) headers intermittently.
When this happened we would crash out:
```
2017/07/25 16:15:13 [error] 2258#0: *2673826 lua entry thread aborted: runtime error: .../lualib/ledge_cache/ledge/ledge.lua:2929: attempt to concatenate local 'res_via' (a table value)
stack traceback:
coroutine 0:
.../lualib/ledge_cache/ledge/ledge.lua: in function 'serve'
../lualib/ledge_cache/ledge/ledge.lua:2214: in function 'e'
.../lualib/ledge_cache/ledge/ledge.lua:1805: in function 'e'
.../lualib/ledge_cache/ledge/ledge.lua:450: in function 'run'
.../lualib/sportradar.lua:94: in function
```
sample response snippet:
```
< Via: 1.1 varnish-v4
< Via: 1.1 varnish-v4
< X-BE-Cache: MISS
< X-FE-Cache: MISS
< X-Varnish: …
```

handle case where Via: header is a table

---

lib/ledge/jobs/revalidate.lua
lib/ledge/util.lua
t/01-unit/util.t

Using string.find and string.sub is about twice as fast as string.gmatch and are JiTable

Use plain string functions in str_split

---

lib/ledge/handler.lua
lib/ledge/state_machine/states.lua

When we fail to get the collapsed forwarding lock we now create a second Redis connection and call `subscribe()` on it.
We then check that the lock key still exists on the main connection before calling `read_reply()` on the second connection which will block until a message is published by the other request.

Rewrite collapsed forwarding lock code. Fixes #140

---

lib/ledge.lua
lib/ledge/handler.lua
t/02-integration/cache.t

Don't schedule garbage collection of the old entity until we have confirmed the new cache entry has been confirmed on both storage and metadata.
Background jobs are submitted on a new connection and so won't be rolled back by the transaction failure.
Additionally make sure we tell storage to delete the just-written entity if the metadata connection fails to commit its transaction.
And only log `exec()` failures if there is an error, rather than just a `nil` response, indicating the watched key was changed.
@pintsized I know you're busy but could you just sanity check this one?

Fixes for metadata transaction abort

---

lib/ledge/state_machine/states.lua
t/02-integration/collapsed_forwarding.t

If waiting on a surrogate request fails for whatever reason (timeout etc) we should attempt to fetch from the origin.
The previous collapsed forwarding implementation was subscribing on the same connection (incorrectly) which would leave us with a broken Redis connection if the timeout window expired.
The new implementation doesn't have this limitation and can continue fetching using the main redis connection

Fetch on collapsed forwarding timeout

---

lib/ledge/cache_key.lua
lib/ledge/handler.lua

This branch moves the functions which actually generate a cache key into a separate module.
They can now be called directly to generate a fresh cache key without having to manually reset the handler instance cache.
Also allows passing a table of values into the generate function so that we can generate cache keys headlessly without having to manipulate the current request variables.
Which will be useful for testing and for a coming bulk PURGE API. 
Supporting this with custom cache key functions is a little weird.
Currently I'm just passing through the vars table to each function.
Those functions will have to check both the custom vars first and then ngx.* output. (See example test)
I'm wondering if it would be worth just always passing a vars table with some sensible values into cache …

Refactor cache key generation

---

t/02-integration/ssl.t
t/02-integration/upstream.t

Allows you to move the socket directory around without moving the whole HTML dir. Handy when you've got the repo on a NFS mount (inside a vagrant VM for example) and resty can't make sockets in the standard dir but can load certs etc.

Move socket locations to new var for portability

---

lib/ledge/util.lua
t/01-unit/util.t

Fixes #166 
`utils.co_wrap` will only return the first 3 yielded values now, so any filters that add extra return values will also have to increase that.
Implementing this with a flexible number of return values is both hard and requires a bunch of extra table creation / unpacking.

Errors in coroutines

---

README.md
lib/ledge/esi/processor_1_0.lua
t/01-unit/processor_1_0.t
t/02-integration/esi.t

Prevent user-provided input (e.g. query strings) from injecting potentially malicious data.
Previously ESI variables were evaluated replaced in the response body *before* processing of ESI include or when/choose tags.  
This allowed the injection of new ESI tags and/or HTML directly into the response body.
ESI variables in ESI include and when/choose tags are now evaluated at the latest possible opportunity and never replaced within the response body.
Variables inside `<esi:vars>` tags could also inject new ESI tags or HTML into the response body allowing XSS attacks.
Now all variables have `<` and `>` characters replaced with their html entity equivalent *unless* the  variable name is prefixed with `RAW_`
e.g.
Escaped:
`<esi:vars>$(QUERY_STRING)</esi:vars>` 
Unescaped: …

SSRF / XSS fixes

---

lib/ledge/storage/redis.lua
t/01-unit/storage.t

Redis storage would roll back if the initial upstream connection failed,
or if the redis connection itself failed, but not if a long running
upstream connection failed midway. This resulted in truncated content
and is most likely to show up with large binaries.

Fixes redis storage bug on failed connection

---

README.md
lib/ledge.lua
lib/ledge/esi/processor_1_0.lua
t/02-integration/esi.t

Cookies will still always be sent to subrequests for ESI includes
(unless disabled in another way), but any cookies blacklisted will not
evaluated in <esi:vars> or inside other esi tags, to prevent accidental
exposure of sensitive data.
This required a little refactoring, which will result in a small
performance increase on pages with lots of ESI cookie expansion.

Feature to blacklist cookies from esi evaluation
